version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat check --info --no-daemon

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  # don't let this fool you, we still build to target java7
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
